"""assignment lecture coverage

Revision ID: 0005
Revises: 0004
Create Date: 2026-05-13
"""
from alembic import op
import sqlalchemy as sa


revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('covers_lecture_from', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('covers_lecture_to', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('covers_lecture_to')
        batch_op.drop_column('covers_lecture_from')

    # ### end Alembic commands ###
